import ../util
import base

proc testCalcRank()=
  assertVal(calcRank(A1), RANK_1, "Invalid rank for A1")
  assertVal(calcRank(B1), RANK_1, "Invalid rank for B1")
  assertVal(calcRank(C1), RANK_1, "Invalid rank for C1")
  assertVal(calcRank(E1), RANK_1, "Invalid rank for E1")
  assertVal(calcRank(G1), RANK_1, "Invalid rank for G1")
  assertVal(calcRank(H1), RANK_1, "Invalid rank for H1")
  assertVal(calcRank(A2), RANK_2, "Invalid rank for A2")
  assertVal(calcRank(B2), RANK_2, "Invalid rank for B2")
  assertVal(calcRank(C2), RANK_2, "Invalid rank for C2")
  assertVal(calcRank(E2), RANK_2, "Invalid rank for E2")
  assertVal(calcRank(G2), RANK_2, "Invalid rank for G2")
  assertVal(calcRank(H2), RANK_2, "Invalid rank for H2")
  assertVal(calcRank(A4), RANK_4, "Invalid rank for A4")
  assertVal(calcRank(B4), RANK_4, "Invalid rank for B4")
  assertVal(calcRank(C4), RANK_4, "Invalid rank for C4")
  assertVal(calcRank(E4), RANK_4, "Invalid rank for E4")
  assertVal(calcRank(G4), RANK_4, "Invalid rank for G4")
  assertVal(calcRank(H4), RANK_4, "Invalid rank for H4")
  assertVal(calcRank(A6), RANK_6, "Invalid rank for A6")
  assertVal(calcRank(B6), RANK_6, "Invalid rank for B6")
  assertVal(calcRank(C6), RANK_6, "Invalid rank for C6")
  assertVal(calcRank(E6), RANK_6, "Invalid rank for E6")
  assertVal(calcRank(G6), RANK_6, "Invalid rank for G6")
  assertVal(calcRank(H6), RANK_6, "Invalid rank for H6")
  assertVal(calcRank(A8), RANK_8, "Invalid rank for A8")
  assertVal(calcRank(B8), RANK_8, "Invalid rank for B8")
  assertVal(calcRank(C8), RANK_8, "Invalid rank for C8")
  assertVal(calcRank(E8), RANK_8, "Invalid rank for E8")
  assertVal(calcRank(G8), RANK_8, "Invalid rank for G8")
  assertVal(calcRank(H8), RANK_8, "Invalid rank for H8")

proc testCalcFile()=
  assertVal(calcFile(A1), FILE_A, "Invalid file for A1")
  assertVal(calcFile(C1), FILE_C, "Invalid file for C1")
  assertVal(calcFile(E1), FILE_E, "Invalid file for E1")
  assertVal(calcFile(G1), FILE_G, "Invalid file for G1")
  assertVal(calcFile(H1), FILE_H, "Invalid file for H1")
  assertVal(calcFile(A2), FILE_A, "Invalid file for A2")
  assertVal(calcFile(B2), FILE_B, "Invalid file for B2")
  assertVal(calcFile(C2), FILE_C, "Invalid file for C2")
  assertVal(calcFile(E2), FILE_E, "Invalid file for E2")
  assertVal(calcFile(G2), FILE_G, "Invalid file for G2")
  assertVal(calcFile(H2), FILE_H, "Invalid file for H2")
  assertVal(calcFile(A4), FILE_A, "Invalid file for A4")
  assertVal(calcFile(B4), FILE_B, "Invalid file for B4")
  assertVal(calcFile(C4), FILE_C, "Invalid file for C4")
  assertVal(calcFile(E4), FILE_E, "Invalid file for E4")
  assertVal(calcFile(G4), FILE_G, "Invalid file for G4")
  assertVal(calcFile(H4), FILE_H, "Invalid file for H4")
  assertVal(calcFile(A6), FILE_A, "Invalid file for A6")
  assertVal(calcFile(B6), FILE_B, "Invalid file for B6")
  assertVal(calcFile(C6), FILE_C, "Invalid file for C6")
  assertVal(calcFile(E6), FILE_E, "Invalid file for E6")
  assertVal(calcFile(G6), FILE_G, "Invalid file for G6")
  assertVal(calcFile(H6), FILE_H, "Invalid file for H6")
  assertVal(calcFile(A8), FILE_A, "Invalid file for A8")
  assertVal(calcFile(B8), FILE_B, "Invalid file for B8")
  assertVal(calcFile(C8), FILE_C, "Invalid file for C8")
  assertVal(calcFile(E8), FILE_E, "Invalid file for E8")
  assertVal(calcFile(G7), FILE_G, "Invalid file for G8")
  assertVal(calcFile(H8), FILE_H, "Invalid file for H8")



  # Testing `PositionIndex`
proc testBoardPosition()=
  assertVal(A1.ord,  0, "invalid ordinal for A1")
  assertVal(B1.ord,  1, "invalid ordinal for B1")
  assertVal(C1.ord,  2, "invalid ordinal for C1")
  assertVal(D1.ord,  3, "invalid ordinal for D1")
  assertVal(E1.ord,  4, "invalid ordinal for E1")
  assertVal(F1.ord,  5, "invalid ordinal for F1")
  assertVal(G1.ord,  6, "invalid ordinal for G1")
  assertVal(H1.ord,  7, "invalid ordinal for H1")
  assertVal(A2.ord,  8, "invalid ordinal for A2")
  assertVal(B2.ord,  9, "invalid ordinal for B2")
  assertVal(C2.ord, 10, "invalid ordinal for C2")
  assertVal(D2.ord, 11, "invalid ordinal for D2")
  assertVal(E2.ord, 12, "invalid ordinal for E2")
  assertVal(F2.ord, 13, "invalid ordinal for F2")
  assertVal(G2.ord, 14, "invalid ordinal for G2")
  assertVal(H2.ord, 15, "invalid ordinal for H2")
  assertVal(A3.ord, 16, "invalid ordinal for A3")
  assertVal(B3.ord, 17, "invalid ordinal for B3")
  assertVal(C3.ord, 18, "invalid ordinal for C3")
  assertVal(D3.ord, 19, "invalid ordinal for D3")
  assertVal(E3.ord, 20, "invalid ordinal for E3")
  assertVal(F3.ord, 21, "invalid ordinal for F3")
  assertVal(G3.ord, 22, "invalid ordinal for G3")
  assertVal(H3.ord, 23, "invalid ordinal for H3")
  assertVal(A4.ord, 24, "invalid ordinal for A4")
  assertVal(B4.ord, 25, "invalid ordinal for B4")
  assertVal(C4.ord, 26, "invalid ordinal for C4")
  assertVal(D4.ord, 27, "invalid ordinal for D4")
  assertVal(E4.ord, 28, "invalid ordinal for E4")
  assertVal(F4.ord, 29, "invalid ordinal for F4")
  assertVal(G4.ord, 30, "invalid ordinal for G4")
  assertVal(H4.ord, 31, "invalid ordinal for H4")
  assertVal(A5.ord, 32, "invalid ordinal for A5")
  assertVal(B5.ord, 33, "invalid ordinal for B5")
  assertVal(C5.ord, 34, "invalid ordinal for C5")
  assertVal(D5.ord, 35, "invalid ordinal for D5")
  assertVal(E5.ord, 36, "invalid ordinal for E5")
  assertVal(F5.ord, 37, "invalid ordinal for F8")
  assertVal(G5.ord, 38, "invalid ordinal for G5")
  assertVal(H5.ord, 39, "invalid ordinal for H5")
  assertVal(A6.ord, 40, "invalid ordinal for A6")
  assertVal(B6.ord, 41, "invalid ordinal for B6")
  assertVal(C6.ord, 42, "invalid ordinal for C6")
  assertVal(D6.ord, 43, "invalid ordinal for D6")
  assertVal(E6.ord, 44, "invalid ordinal for E6")
  assertVal(F6.ord, 45, "invalid ordinal for F6")
  assertVal(G6.ord, 46, "invalid ordinal for G6")
  assertVal(H6.ord, 47, "invalid ordinal for H6")
  assertVal(A7.ord, 48, "invalid ordinal for A7")
  assertVal(B7.ord, 49, "invalid ordinal for B7")
  assertVal(C7.ord, 50, "invalid ordinal for C7")
  assertVal(D7.ord, 51, "invalid ordinal for D7")
  assertVal(E7.ord, 52, "invalid ordinal for E7")
  assertVal(F7.ord, 53, "invalid ordinal for F7")
  assertVal(G7.ord, 54, "invalid ordinal for G7")
  assertVal(H7.ord, 55, "invalid ordinal for H8")
  assertVal(A8.ord, 56, "invalid ordinal for A8")
  assertVal(B8.ord, 57, "invalid ordinal for B8")
  assertVal(C8.ord, 58, "invalid ordinal for C8")
  assertVal(D8.ord, 59, "invalid ordinal for D8")
  assertVal(E8.ord, 60, "invalid ordinal for E8")
  assertVal(F8.ord, 61, "invalid ordinal for F8")
  assertVal(G8.ord, 62, "invalid ordinal for G8")
  assertVal(H8.ord, 63, "invalid ordinal for H8")


proc TestHelpers()=
  doTest "calcRank", testCalcRank()
  doTest "calcFile", testCalcFile()

proc TestTypes()=
  doTest "BoardPosition", testBoardPosition()

when isMainModule:
  TestHelpers()
  TestTypes()
